apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  name: {{ include "postgres.fullname" . }}
type: Opaque
data:
  {{- if ((lookup "v1" "Secret" (.Release.Namespace) (include "postgres.fullname" .)) | len) }}
  postgresAdminPassword: {{ (lookup "v1" "Secret" (.Release.Namespace) (include "postgres.fullname" .)).data.postgresAdminPassword }}
  postgresApiPassword: {{ (lookup "v1" "Secret" (.Release.Namespace) (include "postgres.fullname" .)).data.postgresApiPassword }}
  {{- else }}
  postgresAdminPassword: {{ randAlphaNum 16 | b64enc }}
  postgresApiPassword: {{ randAlphaNum 16 | b64enc }}
  {{- end }}
  postgresAdminUser: {{ "admin" | b64enc }}
  postgresApiUser: {{ "apiuser" | b64enc }}
  postgresDbName: {{ "userapi" | b64enc }}
