apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-api.fullname-postgres" . }}
  labels:
    {{- include "user-api.labels" . | nindent 4 }}
type: Opaque
data:
  postgresAdminUser: {{ "admin" | b64enc }}
  postgresAdminPassword: {{ randAlphaNum 16 | b64enc }}
  postgresApiUser: {{ "apiuser" | b64enc }}
  postgresApiPassword: {{ randAlphaNum 16 | b64enc }}
  postgresDbName: {{ "userapi" | b64enc }}
