{{- if .Values.migrate.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "user-api.labels" . | nindent 4 }}
  name: {{ include "user-api.fullname-migrate" . }}
spec:
  template:
    spec:
      containers:
        - env:
            - name: DB_ADDRESS
              value: {{ include "user-api.db-dnsname" . }}
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: postgresDbName
                  name: {{ include "user-api.fullname-postgres" . }}
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: postgresAdminPassword
                  name: {{ include "user-api.fullname-postgres" . }}
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: postgresAdminUser
                  name: {{ include "user-api.fullname-postgres" . }}
          image: {{ printf "%s:%s" .Values.migrate.image.repository (include "user-api.tag-migrate" .) | quote }}
          imagePullPolicy: {{ .Values.migrate.image.pullPolicy }}
          name: main
      restartPolicy: Never
{{- end }}
