apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "auth-api.labels" . | nindent 4 }}
  name: {{ include "auth-api.fullname" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "auth-api.selectorLabels" . | nindent 6}}
  template:
    metadata:
      annotations:
        podRoller: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "auth-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - args:
            - "--port=80"
            - "--host=0.0.0.0"
            - "auth_api.routers.main:app"
          command: ["uvicorn"]
          env:
            - name: USER_API_URL
              value: {{ default (printf "http://user-api.%s.svc.cluster.local" .Release.Namespace) .Values.userApiUrl | quote }}
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: uvicorn
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
