apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "auth-api.labels" . | nindent 4 }}
  name: {{include "auth-api.fullname" . }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    {{- include "auth-api.selectorLabels" . | nindent 4 }}
  type: ClusterIP
