apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  name: {{ include "postgres.fullname" . }}
spec:
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
  type: ClusterIP
